apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nats-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nats-storage
  local:
    path: /data/nats/pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master-01
---
apiVersion: v1
kind: Service
metadata:
  name: mynats
  labels:
    app: mynats
spec:
  ports:
  - port: 4222
    name: web
  clusterIP: None
  selector:
    app: mynats
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: natstest
spec:
  selector:
    matchLabels:
      app: mynats # has to match .spec.template.metadata.labels
  serviceName: "mynats"  #声明它属于哪个Headless Service.
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mynats # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mynats
        image: nats:latest
        ports:
        - containerPort: 4222
          name: natstest
        volumeMounts:
        - name: www
          mountPath: /usr/share/mynats
  volumeClaimTemplates:   #可看作pvc的模板
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nats-storage"  #存储类名，改为集群中已存在的
      resources:
        requests:
          storage: 1Gi